### PR TITLE
For pull req

### PR DESCRIPTION
**Pull request by Steven-N-Hart**
Marton,
I made some changes here to:
1.  Use different genetic codes (so it works on bacteria) [set in config.txt]
2.  Always uses the mitochondrial genetic code for variants on chrM or chrMT (also M or MT)
3.  Dynamically determine the chromosome names so they don't have to be hard-coded [see config.txt]

### CODE REVIEW

**Comment by marton-munz** [comment]
Thanks very much Steven!
We are now going to look at the changes and get back to you soon!

**Comment by marton-munz** [comment]
Hi Steven,

Thank you for your suggestions! We plan to do the following if you are agreeable:

Could you please give us permission to commit to your forked pull request branch so that we can make the modifications?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

Regarding the @codon_usage option you have proposed:
-  We are very happy to hard-code the use of the mitochondrial code for all genes with chromosome M or MT, while using the standard code for all other genes, as we cannot imagine a situation where a user would want to use the standard code for mitochondrial genes, or vice versa. Thanks very much for drawing our attention to the proper usage of the mitochondrial code!
-  Usage of the 3 letter amino acid code in the p. portion of the annotation is a mandatory requirement of CSN, so unfortunately we cannot allow this flexibility to be added to the CAVA codebase. Of note, if you would like to use the 1 letter amino acid code, this is now possible (though more indirect) in version 1.2.0 of CAVA using the new PROTREF and PROTALT fields.
-   As you know there are complexities around bacterial codes and it is not an area that we have personal expertise in. We therefore don’t feel comfortable with adding this feature to the codebase at this time, but are of course happy for you to continue using your implementation in your personal version of CAVA. We are seeking additional input and will keep in contact with you about this.

With the above changes we think a @codon_usage option is not currently required.

For future reference, if you are introducing a new flag in the config file, please use the Options class in core.py. The constructor of the Options class is the place to define all configuration option flags. You can define a new flag by simply adding a new key to the self.defs dictionary:

self.defs['flagname'] = (type, defaultvalue)

Note that type can either be 'string' or 'boolean'.
This will create a new flag called @flagname with the specified default value.

For example, the @chrom flag you introduced in the config file can be defined this way:

self.defs['chrom'] = ('string', '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,18,20,21,22,X,Y,MT')

The Options class will do all the parsing, so you don't need to open and parse the config file every time you need to access an option. You can simply access the value of your config option by:
options.args['chrom']

Note that options is an instance of Options and is initialized at the beginning of running CAVA. See the line:
options = Options(copts.conf)
This reads the configuration file into the options object.

Since the options object is accessible in the constructor of the SingleJob class, all we need for creating self.chroms is the following line:

self.chroms = options.args['chrom'].strip().split(',')

Therefore the parsing of the config file can be removed from the constructor of SingleJob.

Thanks a lot!

**Comment by Steven-N-Hart** [comment]
Unfortunately, I already have a use case that is using CAVA for tuberculosis annotations - so I need to leave that one in there.  For more information, I used the bacterial code [here](https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi).

You should have write access to this pull request already (I have the box checked).  Can you verify?

Thanks

**Comment by marton-munz** [comment]
Hi Steven. I can confirm that I have write access to this pull request as I have now successfully pushed a commit to your forPullReq branch. The changes should automatically appear in the GitHub pull request code. I'm going to accept the pull request now and merge it into our develop branch. Thanks very much!

**Pull request merged**
